name: delivery_servicos
description: TCC - Delivery de Serviços

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.1.0
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  easy_mask: ^2.0.1
  cached_network_image: ^3.2.1
  rx_shared_preferences: ^3.0.0
  shared_preferences: ^2.0.15
  package_info_plus: ^1.4.2
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  search_cep: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.7.0
  flutter_social_button: ^1.1.4
  badges: ^2.0.2
  money2: ^3.0.0
  flutter_svg:
  open_store: ^0.4.0
  url_launcher: ^6.1.7
  image_picker: ^0.8.6
  flutter_image_compress: ^1.1.3
  date_time_format: ^2.0.1
  #font_awesome_flutter: ^10.2.1

  flutter_modular: ^5.0.3
  get: ^4.6.5

  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  firebase_auth: ^4.1.3
  firebase_messaging: ^14.1.1
  cloud_firestore: ^4.1.0
  google_sign_in: ^5.2.1
  google_maps_place_picker_mb: ^2.0.0-mb.22
  google_maps_flutter: ^2.2.1
  geocoder2: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/